### ISSUE TITLE
reproduction in few-shot classification setting

### ISSUE THREAD

**Issue by shlee625** [chrysts/generative_preconditioner#1]
Hi.
In section 5.1, `WideResNet 28-10` and `ResNet-34` are also used in experiments.
But in `classification/convnet.py`, only `Conv-4` exists. Is there any plan to reproduce the experiments with those 2 architectures?
I want to test on those 2 architectures because I wonder how much memory do they take.
Thank you.

**Comment by chrysts** [comment]
Hi Layla7,

Thank you for your interest to our work.
The memory still fits a 12GB GPU, and we only apply the gradient modulation to the last two convolutions.
I may publish the ResNet-34 one but I need to clean my code first.

**Comment by shlee625** [comment]
> Hi Layla7,
> 
> Thank you for your interest to our work.
> The memory still fits a 12GB GPU, and we only apply the gradient modulation to the last two convolutions.
> I may publish the ResNet-34 one but I need to clean my code first.

Thank you for your reply. It's surprising that the memory fits a 12GB GPU because when I run another reproduction of MAML with `ResNet-12`, it takes almost 23GB memory and takes almost 100 hours. I hope I can experiment with your `ResNet-34` one soon. Thanks again and be safe.

**Comment by chrysts** [comment]
Hi Layla7,

Actually ResNet12 has more parameters than ResNet-34. I think you can do it directly if you try using ResNet-34 (the same structure as in torchvision)

**Comment by shlee625** [comment]
> Hi Layla7,
> 
> Actually ResNet12 has more parameters than ResNet-34. I think you can do it directly if you try using ResNet-34 (the same structure as in torchvision)

Oh, I didn't realize that. Thank you for letting me know.
